name: Blog Posts

on:
  workflow_dispatch:
  schedule:
    # Runs 6 hours
    - cron: '0 */6 * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.furmanp.com/api/rss"
